### ISSUE TITLE
Ember 2.7.0: Error when `model()` returns a promise from `this.store` and query params are in the URL

### ISSUE THREAD

**Issue by aroberts** [knownasilya/ember-query-params#21]
I'm seeing an error when using ember-query-params with Ember 2.7, in a fairly particular set of circumstances.

Preconditions:
- `model()` returns the result of e.g. `this.store.findRecord(...)`, `this.store.query(...)`
- route mixes in AutosubscribeMixin
- page loads with query parameter set in the URL

As far as I can tell, at the time that the action is handled, the `_qpDelegate` property on the controller is null. Please let me know if you have any trouble reproducing this.

Here's my ember/ember-data info and the trace:

```
DEBUG: -------------------------------
DEBUG: Ember             : 2.7.0
DEBUG: Ember Data        : 2.7.0
DEBUG: jQuery            : 2.2.4
DEBUG: -------------------------------
```

```
ember.debug.js:30610 Error while processing route: reports.hello delegate is not a function TypeError: delegate is not a function
    at Class._qpChanged (http://localhost:4200/assets/vendor.js:36611:7)
    at Object.sendEvent (http://localhost:4200/assets/vendor.js:30625:18)
    at notifyObservers (http://localhost:4200/assets/vendor.js:34527:25)
    at propertyDidChange (http://localhost:4200/assets/vendor.js:34347:7)
    at Object.notify (http://localhost:4200/assets/vendor.js:29194:9)
    at chainsDidChange (http://localhost:4200/assets/vendor.js:34443:9)
    at Object.propertyDidChange (http://localhost:4200/assets/vendor.js:34346:7)
    at Object.set (http://localhost:4200/assets/vendor.js:34737:34)
    at http://localhost:4200/assets/vendor.js:39337:37
    at Array.forEach (native)
```

**Comment by SirZach** [comment]
Getting the same issue on `ember 2.4.6`

**Comment by knownasilya** [comment]
Unfortunately these are bugs in Ember and we'll all have to wait till we have some improvements in the QP/Router department, probably 2.9 or 2.10 of Ember. @nathanhammond is tackling that work.

**Comment by SirZach** [comment]
Happy to hear QPs are getting some love. This addon is a really awesome concept btw, exactly what I was looking for.

**Comment by knownasilya** [comment]
Hopefully in the future it'll be even simpler, like just a service without the needed mixins.

**Comment by jasonmit** [comment]
I was able to work around this by moving the subscriber logic from beforeModel to setupController.
